services:
  - type: web
    name: statoscope-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    disk:
      name: statoscope-disk
      mountPath: /app/uploads
      sizeGB: 1
